### PR TITLE
Add whitelisted SPL tokens to show proper tickers

### PR DESCRIPTION
**Pull request by sponomarev**
# Checklist

- [x] App update process has been followed 
- [x] Target branch is `develop` 
- [x] Application version has been bumped 

CI status note:
- [Sonarcloud / sonarcloud (pull_request) ](https://github.com/LedgerHQ/app-solana/actions/runs/9110302334/job/26062992620?pr=80) misconfiguration on the CI side?. `Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator`
- [Code style check / Check misspellings (pull_request) ](https://github.com/LedgerHQ/app-solana/actions/runs/9110302333/job/26062992610?pr=80) Typo in unrelated code that also present in the upsteam branch. Not sure why it wasn't triggered there
https://github.com/LedgerHQ/app-solana/blob/5138865dad24f6583a1a954d5633e215d84db5a1/src/ui/menu_nbgl.c#L87
https://github.com/LedgerHQ/app-solana/blob/5138865dad24f6583a1a954d5633e215d84db5a1/src/ui/menu_nbgl.c#L94
https://github.com/LedgerHQ/app-solana/blob/5138865dad24f6583a1a954d5633e215d84db5a1/src/ui/menu_nbgl.c#L101

- [Compilation & tests / Run ragger tests using the reusable workflow / ](https://github.com/LedgerHQ/app-solana/actions/runs/9110302489/job/26063049501?pr=80) Same failure [present](https://github.com/LedgerHQ/app-solana/actions/runs/8813366706/job/24191048392) on the latest `develop` branch.

### CODE REVIEW

**Comment by sponomarev** [comment]
> this is going to need to be device gated on the S. won't fit afaik

@t-nelson Will you be able to explain what do you mean? Any changes needed?

**Comment by jnwng** [comment]
> > this is going to need to be device gated on the S. won't fit afaik
> 
> @t-nelson Will you be able to explain what do you mean? Any changes needed?

there may not be enough memory on device to store the mapping of addresses to symbols. did you already test this on the emulator?

**Comment by sponomarev** [comment]
> there may not be enough memory on device to store the mapping of addresses to symbols. did you already test this on the emulator?

@jnwng Yep! We did! In addition to end-to-end tests with [Ragger](https://github.com/LedgerHQ/ragger), manual QA was performed on the real Nano S device and Speculos as well. To check that everything works well, I've been asked to make sure that BTC/ETH + Solana + Exchange apps fit Nano S devices. Everything is smooth.

```
$ python3 -m ledgerblue.listApps --targetId 0x31100004

[{'flags': 1952336, 'hash_code_data': b'T\xf4\xff\x8f4Bw\x1c2\x9d\xcbp/z/\x84\xe9\xffx\x18|\x0f\xaaI~\xa9E\xe4o\xe3P\xc4', 'hash': b"\x1c`'\x1a\x9dL\xc3I\x816\x00\xfc\x1d\x86\xce\x01h\x19*\xb29\xb0\xb9\xda\xfd\x0c\xb2\x99\xdc\x1bB\xcf", 'name': 'Bitcoin'},
{'flags': 901712, 'hash_code_data': b'\x8f\xc9\xac8\xc0\x1fo\xea\xf3@\xb7\xe3 \x18\x8e\xbf\x01W5\xde\xea\xf5\xbd\xe2\xef\x131G\xdb\x0e8\x0e', 'hash': b'S\x85GG\x1ey\xf4`OGk\x10a\x94\xdd!2\x1a\x1b\xce\x81\x11\xd3U@_\x19\xd6B"S\x1e', 'name': 'Exchange'}]
[{'flags': 1345536, 'hash_code_data': b'|H\x8c\xabg\x02\xca\xd5\xdd\x95\x8al\xca\x81J\xe1\xb7\x838\x0f\xa4)Z\xfb\xe2g\xd1r\xd1\x01\xf3K', 'hash': b'\xc6o\x9fj\xd97r\xbb\xc7\xfdB\xe9\xe2\x9e\xdd\xc03\x88\xc5\xa1`\x08\xb3\x0e\x10\x83\xc2;z\xd2\xa2\xff', 'name': 'Solana'}]
```

**Comment by fbeutin-ledger** [comment]
CI is failing on functional tests for Flex and Stax during snapshots check
This is due to the Stax and Flex SDKs fonts and layouts having been updated since the test was last ran
Since the tests are OK on Nano devices it's not blocking
Info : Tests snapshots can be regenerated with `--golden_run` option

**Comment by sponomarev** [comment]
@fbeutin-ledger @vforgeoux-ledger  Functional tests snapshots for Flex and Stax  has been updated in #92

**Pull request merged**
