### PR TITLE
Compute budget and split stake instruction support 

### PR DESCRIPTION
**Pull request by 0xMMBD**
Changeset:

* Added split-stake instruction support for:
    * SystemTransfer + SystemAllocate + SystemAssign + StakeSplit
    * SystemTransfer + SystemAllocateWithSeed + StakeSplit
   
* Compute Budget instruction
    * request heap frame
    * set compute unit price
    * request units
    * set compute unit limit

### CODE REVIEW

**Comment by 0xMMBD** [comment]
* Change ComputeBudget instruction to display Max fees

**Comment by 0xMMBD** [comment]
@sponomarev Unable to reproduce and fix errors with the ragger tests for stax and flex. Problem is visible even on the develop branch. 
Example job logs(run on commit https://github.com/LedgerHQ/app-solana/commit/4d88a451ccdd9e62ee7791fbc2df8aa1c26e8ce6): https://github.com/blockydevs/app-solana/actions/runs/10800057270/job/29957267466

**Comment by 0xMMBD** [comment]
Looks like the tests are failing on this screen (but hard to say with 100% certainty)

And I'm not able to reproduce it locally as it was shown here: https://github.com/LedgerHQ/app-solana/pull/90#issuecomment-2341959931

**Comment by sponomarev** [comment]
@0xMMBD It seems that there were some SDK updates that slightly changed flex and stax UI. Using the latest dev tools I was able to reproduce the issue and update golden snapshots. You can check it in https://github.com/blockydevs/app-solana/pull/22

**Comment by 0xMMBD** [comment]
@sponomarev fixes for the tests are merged here already

**Comment by 0xMMBD** [comment]
@tdejoigny-ledger is 1.5.2 ok for you?

**Comment by 0xMMBD** [comment]
@tdejoigny-ledger https://github.com/LedgerHQ/app-solana/pull/94

**Review by tdejoigny-ledger — APPROVED** [review]

**Pull request merged**
