### PR TITLE
Improvements of the Solana application code performed during the swap implementation

### PR DESCRIPTION
**Pull request by fbeutin-ledger**
This changes are not Swap related
They are however necessary for the Swap feature implementation

### CODE REVIEW

**Comment by t-nelson** [comment]
i also don't see how any of these changes relate, let alone qualify as prerequisite, to adding support for "swap"

can you create a design issue for adding swap?  it's not implemented today on purpose. i raised issue on discord a couple weeks ago, but not sure if you're there to see it

**Comment by askibin** [comment]
I agree, this needs to wait. We have refactoring changes pending and off-chain transaction signing feature that is needed urgently. I'll raise a PR this week and after it merged we can look at the swap feature.

**Comment by fbeutin-ledger** [comment]
Hello Alexey, I'm looking forward to your PR and I'll adapt mine accordingly
I've cut the PR in detailed commits, each with a specific scope so I'm hopeful about the conflicts being localized

Basically this PR contains:
- clear handling of global variables (when run as libs global variables need to be handled very carefully)
- misc improvements that I made along the way (remove deprecated calls, use defined values instead of arbitrary, ...)
- splitting of UI handling from input parsing in order to reuse the input parsing for the swap flow

**Comment by askibin** [comment]
can we close this?

**Pull request closed without merging**
