### PR TITLE
Add support for off-chain message signatures and refactor the code

### PR DESCRIPTION
**Pull request by askibin**

### CODE REVIEW

**Comment by fbeutin-ledger** [comment]
The Sonarcloud  CI seems to fail on PR from forks, to investigate if it happens regularly
In the meantime no need to block this PR

**Comment by fbeutin-ledger** [comment]
Sonarcould passed here
https://github.com/LedgerHQ/app-solana/actions/runs/3203142734

**Comment by grimAgent** [comment]
Hey! Sorry to bother here, didn't know where to ask. Is this supposed to be live on the ledger solana app already?

**Comment by nathantannar4** [comment]
Also wondering when 1.3 is scheduled for release

**Comment by martincik** [comment]
Would be great to get the 1.3.0 release out soon.

**Pull request merged**
